#!/bin/bash

#should I do this on startvnc?
vglclient &

XFCE_PANEL_MIGRATE_DEFAULT=true startxfce4 &

#cat << EOF > script
#BEGIN
#    LOADIMAGE('$(find $INPUT_DIR -name "*.nii.gz")')
#END.
#EOF

if [ -f /input/fib.gz ]; then
	vglrun dsi_studio /input/fib.gz &
fi
if [ -f /input/src.gz ]; then
	vglrun dsi_studio /input/src.gz &
fi
if [ -f /input/track.tck ]; then
	vglrun dsi_studio /input/track.tck &
fi
if [ -f /input/track.trk ]; then
	vglrun dsi_studio /input/track.trk &
fi
if [ -f /input/tt.gz]; then
	vglrun dsi_studio /input/tt.gz &
fi

pid=$!
echo $pid > /pid

#maximize!
sleep 4
id=`wmctrl -pl | grep " $pid " | cut -f 1 -d " "`
wmctrl -i -r $id -b add,fullscreen

